### ISSUE TITLE
[SP2019]Printing

### ISSUE THREAD

**Issue by Adimote** [sourcebots/tasks#115]
- [x] Rules
- [x] Electronics lab handouts
- [ ] ~Programming lab handouts (#103)~
- [x] Maps of campus (to likely go in #19)
- [x] Schedules of the day - available at https://github.com/sourcebots/tasks/issues/110
- [ ] ~Cube Markers (part of #93)~
- [ ] ~Arena Markers~
- [ ] Score sheets (design is part of #153)
- [x] Signage #135
- [x] Equipment borrowing forms (#129)
- [x] Mentor guidance sheet (see https://github.com/sourcebots/tasks/issues/103#issuecomment-517936728)
- [ ] Kit cheat sheet (cc @trickeydan)

Note: this intentionally doesn't cover the certificates, which are #138.

**Comment by JennyLouise** [comment]
I'll print everything we need* on the 10th of August, just need to be sent the files when they're ready to go.

*Are cube markers and arena markers needed sooner?

**Comment by trickeydan** [comment]
> *Are cube markers and arena markers needed sooner?

We won't know what type of markers we are using until 27th July when the kit is frozen.

**Comment by JennyLouise** [comment]
I assume we'll need those before the weekend of the competition though? I'm away from the 27th July - 4th August. I can print cube and arena markers on the 5th if that's helpful, if they're needed before then then someone else will have to do them.

**Comment by Adimote** [comment]
We could just print both kinds of markers though?

**Comment by trickeydan** [comment]
> We could just print both kinds of markers though?

This might be the right solution here.

**Comment by RealOrangeOne** [comment]
@JennyLouise printed things.
