### ISSUE TITLE
[SP2019]Create Compstate

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#51]
We've got 16 teams this year, up from our usual 10. This makes it harder to copy/paste from previous years.

Subtasks:
- [x] Plan overall match timings
- [x] Plan league matches #68
- [x] Plan knockout matches #69
- [x] Create scoring logic https://github.com/sourcebots/compstate-smallpeice2019/pull/1
- [ ] Create score-entry and data-format #153

**Comment by PeterJCLaw** [comment]
This was blocked on knowing the game and numbers of teams, I don't think this is blocked any more.

**Comment by PeterJCLaw** [comment]
https://github.com/sourcebots/compstate-smallpeice2019

**Comment by PeterJCLaw** [comment]
@joe9599 can you confirm what space we have in SUSU for teams to be in? Currently the compstate has Bar 2 and Bar 3 in the [layout](https://github.com/sourcebots/compstate-smallpeice2019/blob/master/layout.yaml) as that's what I'd assumed would be the case. This may not matter a lot if we only have a single shepherd (or no shepherd), but as this was the main thing which I think was outstanding here it would be good to close it off.

**Comment by PeterJCLaw** [comment]
@joe9599 Separately, the system supports displaying names for the teams; do we want to use that (rather than "Team 4" etc.)? If so, have we told the competitors?

**Comment by PeterJCLaw** [comment]
The teams are all in Bar 2.

**Comment by PeterJCLaw** [comment]
This is created.
